name: deploy

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: git config
        run: |
          git config --global user.name actions
          git config --global user.email actions@github.com
      - name: build
        run: |
          npm install
          npm run build
      - name: push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          TAG=`date +%Y%m%d%H%M%S`-release
          rm -rf docs
          mv build docs
          git add -f docs
          git commit -m 'deploy action'
          git tag -a $TAG -m 'deploy action'
          git push origin master
          git push origin $TAG
